In [1]:
import pandas as pd

In [2]:
!uv add pandas pyarrow

Resolved 108 packages in 2ms
Checked 10 packages in 0.99ms

In [4]:
import pandas as pd

In [5]:
df = pd.read_parquet('https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet')

In [6]:
df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [7]:
len(df)

46912

In [9]:
df.dtypes

VendorID                          int32
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag                  str
RatecodeID                      float64
PULocationID                      int32
DOLocationID                      int32
passenger_count                 float64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                    float64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [12]:
print(df["ehail_fee"].unique())
print(df["trip_type"].unique())
print(df["cbd_congestion_fee"].unique())

[nan]
[ 1.  2. nan]
[ 0.    0.75 -0.75]

In [18]:
df_parquet = pd.read_parquet(
    "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
)

df_parquet.to_csv("green_tripdata_2025-11.csv", index=False)

dtype = {
    "VendorID": "Int64",
    "passenger_count": "Int64",
    "trip_distance": "float64",
    "RatecodeID": "Int64",
    "store_and_fwd_flag": "string",
    "PULocationID": "Int64",
    "DOLocationID": "Int64",
    "payment_type": "float64",
    "fare_amount": "float64",
    "extra": "float64",
    "mta_tax": "float64",
    "tip_amount": "float64",
    "tolls_amount": "float64",
    "improvement_surcharge": "float64",
    "total_amount": "float64",
    "congestion_surcharge": "float64",
    "ehail_fee": "float64",
    "trip_type": "float64",
    "cbd_congestion_fee": "float64"
}

parse_dates = [
    "lpep_pickup_datetime",
    "lpep_dropoff_datetime"
]

df = pd.read_csv(
    "green_tripdata_2025-11.csv",
    dtype=dtype,
    parse_dates=parse_dates
)

In [17]:
df.dtypes

VendorID                          Int64
lpep_pickup_datetime     datetime64[us]
lpep_dropoff_datetime    datetime64[us]
store_and_fwd_flag               string
RatecodeID                        Int64
PULocationID                      Int64
DOLocationID                      Int64
passenger_count                   Int64
trip_distance                   float64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
ehail_fee                       float64
improvement_surcharge           float64
total_amount                    float64
payment_type                      Int64
trip_type                       float64
congestion_surcharge            float64
cbd_congestion_fee              float64
dtype: object

In [20]:
df['lpep_pickup_datetime']

0       2025-11-01 00:34:48
1       2025-11-01 00:18:52
2       2025-11-01 01:03:14
3       2025-11-01 00:10:57
4       2025-11-01 00:03:48
                ...
46907   2025-11-30 19:58:34
46908   2025-11-30 19:34:00
46909   2025-11-30 21:46:46
46910   2025-11-30 21:00:00
46911   2025-11-30 23:26:00
Name: lpep_pickup_datetime, Length: 46912, dtype: datetime64[us]

In [21]:
!uv add sqlalchemy psycopg2-binary

Resolved 107 packages in 2.44s
Prepared 1 package in 132ms
░░░░░░░░░░░░░░░░░░░░ [0/3] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 3 packages in 3.21s
 + greenlet==3.5.1
 + psycopg2-binary==2.9.12
 + sqlalchemy==2.0.49

In [22]:
from sqlalchemy import create_engine
#posgresql://user:pass@localhost:port_No/db_name
engine = create_engine("postgresql://root:root@localhost:5432/ny_taxi")

In [24]:
df.head(0).to_sql(name='green_taxi_data',con=engine,if_exists='replace')

0

In [25]:
#You can use 'next' to iterate and look at all chunks -- each time you run next(df_iter) and print the df it will print the next chunk of df.
df = next(df_iter)

NameError: name 'df_iter' is not defined

In [27]:
df_iter = pd.read_csv(
    "green_tripdata_2025-11.csv",
    dtype=dtype,
    parse_dates=parse_dates,
    chunksize=10000
)

In [28]:
#You can use 'next' to iterate and look at all chunks -- each time you run next(df_iter) and print the df it will print the next chunk of df.
df = next(df_iter)

In [30]:
!uv add tqdm

Resolved 108 packages in 822ms
░░░░░░░░░░░░░░░░░░░░ [0/1] Installing wheels...                                 warning: Failed to hardlink files; falling back to full copy. This may lead to degraded performance.
         If the cache and target directories are on different filesystems, hardlinking may not be supported.
         If this is intentional, set `export UV_LINK_MODE=copy` or use `--link-mode=copy` to suppress this warning.
Installed 1 package in 219ms
 + tqdm==4.67.3

In [31]:
from tqdm.auto import tqdm

In [32]:
for df_chunk in tqdm(df_iter):
    df_chunk.to_sql(name='green_taxi_data',con=engine,if_exists='append')

0it [00:00, ?it/s]

In [3]:
#Importing ZOnes look up table 
url = 'https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv'

In [4]:
zones_df = pd.read_csv(url)

In [5]:
zones_df.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [6]:
len(zones_df)

265

In [7]:
from sqlalchemy import create_engine

In [10]:
engine = create_engine('postgresql://root:root@localhost:5432/ny_taxi')

In [11]:
zones_df.to_sql(con=engine, name='zones_lookup', if_exists='replace')

265